export const TILE = 64;

export const LEVELS = [
  {
    id: 'origin',
    name: '起源之地',
    sub: '旅行者的第一段旅程',
    rows: [
      '########################################',
      '#..F....F....F...........F.......F.....#',
      '#..TTTTTTTT.......#############........#',
      '#..T......T...T..#bbbbbbbbbbbbb#.......#',
      '#..T......T......#bbbbbEEEbbbbb#.......#',
      '#..TTTTT..p.,....#bbbbbbbbbbbbb#.......#',
      '#.TT..T...p...T..#bbbbbbbbbbbbb#.......#',
      '#....T....p...,..#bbbbbbbbbbbbb#.......#',
      '#..T......p......#bbbbbbbbbbbbb#.......#',
      '#..WWWW...p.....F.######G######........#',
      '#..WWWW...p......pppppppp..............#',
      '#..WWWW...p......p......p..............#',
      '#..WWWW...p......p......T......WW......#',
      '#..T......p......p..........F..WW.R....#',
      '#....T....p......p.........T...WW......#',
      '#.....T...p......p....T........WW......#',
      '#..B......p......p..........F..WW...R..#',
      '#T....T...p......p......,.T....WW......#',
      '#..T......p......p.............WW......#',
      '#....T....ppppppppppppppppppppp==pppppp#',
      '#..T.............p.........T...==......#',
      '#....T......F....p.............WW..T...#',
      '#......T.........p.............WW.R....#',
      '#................p....T.....F..........#',
      '#.....Sppppppppppp..,..................#',
      '#..F....T........p............R........#',
      '#....T...........p.........,..T........#',
      '#..T...R................F..............#',
      '#..R...T.......T.................T.....#',
      '########################################',
    ],
    legend: {
      '#': 'wall',
      '.': 'grass',
      ',': 'tallgrass',
      'p': 'path',
      'T': 'tree',
      'B': 'bush',
      'R': 'rock',
      'W': 'water',
      'F': 'flower',
      'S': 'spawn',
      'b': 'arena',
      'G': 'gate',
      'E': 'exit',
      '=': 'bridge',
    },
    spawn: { tx: 6.5, ty: 24.5 },
    boss: { tx: 24.5, ty: 5.5 },
    exit: { tx: 24.5, ty: 4.5 },
    arena: { x0: 18, y0: 3, x1: 30, y1: 8 },
    gate: { tx: 24, ty: 9 },
    enemies: [
      { type: 'mossbeast', tx: 13.5, ty: 21.5 },
      { type: 'mossbeast', tx: 20.5, ty: 23.5 },
      { type: 'mossbeast', tx: 28.5, ty: 25.5 },
      { type: 'mossbeast', tx: 9.5, ty: 26.5 },
      { type: 'mossbeast', tx: 2.5, ty: 8.5 },
      { type: 'mossbeast', tx: 4.5, ty: 15.5 },
      { type: 'mossbeast', tx: 11.5, ty: 1.5 },
      { type: 'mossbeast', tx: 23.5, ty: 11.5 },
      { type: 'mossbeast', tx: 35.5, ty: 13.5 },
      { type: 'mossbeast', tx: 37.5, ty: 16.5 },
      { type: 'mossbeast', tx: 35.5, ty: 20.5 },
      { type: 'dewsprit', tx: 12.5, ty: 6.5 },
      { type: 'dewsprit', tx: 2.5, ty: 2.5 },
      { type: 'dewsprit', tx: 33.5, ty: 19.5 },
      { type: 'dewsprit', tx: 37.5, ty: 14.5 },
    ],
    chests: [{ tx: 6.5, ty: 3.5 }],
    coins: [
      { tx: 33.5, ty: 21.5, n: 5 },
      { tx: 2.5, ty: 20.5, n: 4 },
      { tx: 11.5, ty: 2.5, n: 3 },
      { tx: 26.5, ty: 14.5, n: 3 },
    ],
    signposts: [
      { tx: 8.5, ty: 24.5, text: '旅行者，向深处探索吧。遗迹守卫沉睡在北方。' },
      { tx: 16.5, ty: 19.5, text: '西边森林藏着秘密，东边河流对面很危险。' },
    ],
  },
];

export const CHARACTERS = [
  {
    id: 'aster',
    name: 'Aster',
    title: '疾风旅人',
    role: '近战 · 灵活',
    desc: '在风中长大的年轻冒险者，腰间的短刃快如闪电。身披旅行斗篷，永远走在第一缕晨光里。',
    weapon: '短刃 · 旅风',
    attackType: 'melee',
    color: '#3ec6a8',
    colorDeep: '#1f8f78',
    portrait: 'aster',
  },
  {
    id: 'liora',
    name: 'Liora',
    title: '星语者',
    role: '远程 · 控制',
    desc: '与星尘为伴的神秘少女，手中的星杖能唤起坠落的光。轻盈、安静，却照亮整条旅途。',
    weapon: '星杖 · 暮星',
    attackType: 'ranged',
    color: '#8a7bff',
    colorDeep: '#5b4ad6',
    portrait: 'liora',
  },
];

export const SKILLS = {
  aster: {
    attack: { name: '短刃连斩', cd: 0.24, dmg: 12, range: 84, arc: 2.2 },
    skill1: { name: '疾行斩', cd: 4.5, dmg: 20, dash: 250, width: 60 },
    skill2: { name: '旋刃', cd: 6.5, dmg: 24, radius: 105 },
  },
  liora: {
    attack: { name: '星矢', cd: 0.34, dmg: 14, speed: 560, size: 7 },
    skill1: { name: '星落', cd: 5.0, dmg: 34, radius: 120, speed: 480, maxDist: 420 },
    skill2: { name: '星环', cd: 6.5, dmg: 26, radius: 140 },
  },
};

export const ENEMIES = {
  mossbeast: {
    name: '苔壳兽',
    kind: 'melee',
    hp: 42,
    speed: 118,
    r: 20,
    dmg: 9,
    aggro: 300,
    attackRange: 52,
    windup: 0.5,
    attackCd: 1.15,
    coin: 8,
    score: 100,
    color: '#6fae4e',
  },
  dewsprit: {
    name: '晶露灵',
    kind: 'ranged',
    hp: 30,
    speed: 92,
    r: 17,
    dmg: 8,
    aggro: 340,
    keepMin: 200,
    keepMax: 300,
    projSpeed: 270,
    attackCd: 1.9,
    coin: 6,
    score: 120,
    color: '#58c8e8',
  },
  relicguard: {
    name: '遗迹守卫',
    kind: 'boss',
    hp: 520,
    speed: 95,
    speed2: 150,
    r: 46,
    dmg: 14,
    slamDmg: 18,
    slamR: 130,
    waveDmg: 12,
    volleyDmg: 10,
    aggro: 9999,
    coin: 100,
    score: 1000,
    color: '#9a8f7c',
  },
};

export const CONFIG = {
  player: {
    speed: 300,
    boostMult: 1.72,
    r: 15,
    hpMax: 100,
    staminaMax: 100,
    staminaDrain: 34,
    staminaRegen: 24,
    staminaDelay: 0.6,
    invuln: 0.9,
  },
  zoom: {
    base: 1.0,
    max: 1.05,
    min: 0.92,
  },
  camera: {
    lead: 0.14,
  },
};

export function tileToWorld(tx, ty) {
  return { x: (tx + 0.5) * TILE, y: (ty + 0.5) * TILE };
}

export function worldToTile(x, y) {
  return { tx: Math.floor(x / TILE), ty: Math.floor(y / TILE) };
}
